$(document).ready(function(event){
    $("#design").click(function(){
        $(".sec1").hide();
        $(".click1").show();
    });
    $("#design1").click(function(){
        $(".sec1").show();
        $(".click1").hide();
    });
    $("#dev").click(function(){
        $(".sec2").hide();
        $(".click2").show();
    });
    $("#dev1").click(function(){
        $(".sec2").show();
        $(".click2").hide();
    });
     $("#product").click(function(){
        $(".sec3").hide();
        $(".click3").show();
     });
     $("#product1").click(function(){
        $(".sec3").show();
        $(".click3").hide();
     });
 
     event.preventDefault(); 
});